In [45]:
import pandas as pd 
from statsbombpy import sb
import numpy as np

In [46]:
competitions = sb.competitions()
competitions

C:\Users\sivas\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-07-15T14:15:54.671676,2024-07-15T14:17:00.877356,2024-07-15T14:17:00.877356,2024-07-15T14:15:54.671676
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-06-13T07:51:02.452825,None,None,2024-06-13T07:51:02.452825
3,16,4,Europe,Champions League,male,False,False,2018/2019,2024-06-12T07:44:38.559714,2021-06-13T16:17:31.694,None,2024-06-12T07:44:38.559714
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
...,...,...,...,...,...,...,...,...,...,...,...,...
69,55,43,Europe,UEFA Euro,male,False,True,2020,2024-04-16T12:44:40.558402,2024-04-16T12:47:18.505110,2024-04-16T12:47:18.505110,2024-04-16T12:44:40.558402
70,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2024-02-12T14:45:05.702250,2021-06-13T16:17:31.694,None,2024-02-12T14:45:05.702250
71,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2024-02-13T13:27:17.178263,2024-02-13T13:30:52.820588,2024-02-13T13:30:52.820588,2024-02-13T13:27:17.178263
72,72,107,International,Women's World Cup,female,False,True,2023,2024-07-14T16:59:48.469596,2024-07-14T17:01:38.887279,2024-07-14T17:01:38.887279,2024-07-14T16:59:48.469596
73,72,30,International,Women's World Cup,female,False,True,2019,2024-02-13T09:41:26.379767,2021-06-13T16:17:31.694,None,2024-02-13T09:41:26.379767

In [47]:
competitions[competitions["competition_name"]=='1. Bundesliga']

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-07-15T14:15:54.671676,2024-07-15T14:17:00.877356,2024-07-15T14:17:00.877356,2024-07-15T14:15:54.671676
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381

In [48]:
matches = sb.matches(competition_id=9, season_id=281)
matches[matches['home_team']=='Bayer Leverkusen']

C:\Users\sivas\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3895302,2024-04-14,17:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Werder Bremen,5,0,available,...,2024-05-10T17:03:59.613154,29,Regular Season,BayArena,Harm Osmers,Xabier Alonso Olano,Ole Werner,1.1.0,2,2
4,3895348,2024-05-18,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Augsburg,2,1,available,...,2024-05-20T10:33:09.140760,34,Regular Season,BayArena,Matthias Jöllenbeck,Xabier Alonso Olano,Jess Christian Thorup,1.1.0,2,2
5,3895286,2024-03-30,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Hoffenheim,2,1,available,...,2024-05-08T03:36:21.320065,27,Regular Season,BayArena,Deniz Aytekin,Xabier Alonso Olano,Pellegrino Matarazzo,1.1.0,2,2
7,3895250,2024-02-23,21:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,FSV Mainz 05,2,1,available,...,2024-05-08T00:38:33.864825,23,Regular Season,BayArena,Timo Gerach,Xabier Alonso Olano,Bo Henriksen,1.1.0,2,2
8,3895266,2024-03-10,20:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Wolfsburg,2,0,available,...,2024-04-28T10:29:53.455142,25,Regular Season,BayArena,Daniel Siebert,Xabier Alonso Olano,Niko Kovač,1.1.0,2,2
10,3895180,2023-12-17,18:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Eintracht Frankfurt,3,0,available,...,2024-03-31T21:08:00.046656,15,Regular Season,BayArena,Christian Dingert,Xabier Alonso Olano,Dino Toppmöller,1.1.0,2,2
12,3895121,2023-10-29,18:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Freiburg,2,1,available,...,2023-11-22T05:11:07.603363,9,Regular Season,BayArena,Daniel Siebert,Xabier Alonso Olano,Christian Streich,1.1.0,2,2
13,3895107,2023-10-08,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,FC Köln,3,0,available,...,2024-01-06T10:35:32.456060,7,Regular Season,BayArena,Felix Zwayer,Xabier Alonso Olano,Steffen Baumgart,1.1.0,2,2
15,3895139,2023-11-12,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Union Berlin,4,0,available,...,2024-01-30T20:45:30.579373,11,Regular Season,BayArena,Timo Gerach,Xabier Alonso Olano,Urs Fischer,1.1.0,2,2
16,3895086,2023-09-24,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,FC Heidenheim,4,1,available,...,2024-01-01T09:52:59.525330,5,Regular Season,BayArena,Christian Dingert,Xabier Alonso Olano,Frank Schmidt,1.1.0,2,2
17,3895320,2024-04-27,19:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,VfB Stuttgart,2,2,available,...,2024-05-13T17:38:39.789677,31,Regular Season,BayArena,Felix Zwayer,Xabier Alonso Olano,Sebastian Hoeneß,1.1.0,2,2
21,3895232,2024-02-10,19:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Bayern Munich,3,0,available,...,2024-05-07T19:36:17.578845,21,Regular Season,BayArena,Felix Zwayer,Xabier Alonso Olano,Thomas Tuchel,1.1.0,2,2
22,3895210,2024-01-27,19:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Borussia Mönchengladbach,0,0,available,...,2024-04-28T11:15:03.792111,19,Regular Season,BayArena,Deniz Aytekin,Xabier Alonso Olano,Gerardo Seoane Castro,1.1.0,2,2
25,3895182,2023-12-20,21:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Bochum,4,0,available,...,2024-03-27T11:25:34.494440,16,Regular Season,BayArena,Daniel Schlager,Xabier Alonso Olano,Thomas Letsch,1.1.0,2,2
27,3895158,2023-12-03,18:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Borussia Dortmund,1,1,available,...,2024-05-07T20:02:31.877343,13,Regular Season,BayArena,Daniel Siebert,Xabier Alonso Olano,Edin Terzić,1.1.0,2,2
31,3895067,2023-09-02,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,Darmstadt 98,5,1,available,...,2023-10-29T03:14:50.549747,3,Regular Season,BayArena,Sven Jablonski,Xabier Alonso Olano,Torsten Lieberknecht,1.1.0,2,2
33,3895052,2023-08-19,16:30:00.000,Germany - 1. Bundesliga,2023/2024,Bayer Leverkusen,RB Leipzig,3,2,available,...,2023-11-21T13:34:09.912520,1,Regular Season,BayArena,Felix Brych,Xabier Alonso Olano,Marco Rose,1.1.0,2,2

In [49]:
BayerWerder = sb.
BayerWerder

SyntaxError: invalid syntax (1213884691.py, line 1)

In [ ]:
df=pd.read_csv("europaFinal.csv")

In [61]:
df.head()

,minute,second,teamId,x,y,period,type,outcome,playerId,endX,endY,x1_bin
2,0,0.0,Manchester United,49.9,50.0,FirstHalf,Pass,Successful,18.0,31.5,59.6,5
119,6,11.0,Manchester United,65.4,96.8,FirstHalf,Pass,Successful,18.0,63.3,87.8,7
130,6,55.0,Manchester United,69.8,30.3,FirstHalf,Pass,Successful,18.0,74.4,18.8,8
133,7,1.0,Manchester United,84.3,23.3,FirstHalf,Pass,Successful,18.0,86.0,20.0,10
185,12,20.0,Manchester United,39.0,64.8,FirstHalf,Pass,Successful,18.0,32.8,72.9,3

In [ ]:
df= df.loc[(df['playerId']==18.0) & (df["teamId"]=='Manchester United')& (df["type"]=="Pass")&(df["outcome"]=="Successful")]
df

In [54]:
xt_grid = pd.read_csv("xT_Grid.csv", header = None)

In [55]:
xt_grid

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.006383,0.007796,0.008449,0.009777,0.011263,0.012483,0.014736,0.017451,0.021221,0.027563,0.034851,0.037926
1,0.007501,0.008786,0.009424,0.010595,0.012147,0.013845,0.016118,0.018703,0.024015,0.029533,0.040670,0.046477
2,0.008880,0.009777,0.010013,0.011105,0.012692,0.014291,0.016856,0.019351,0.024122,0.028552,0.054911,0.064426
3,0.009411,0.010827,0.010165,0.011324,0.012626,0.014846,0.016895,0.019971,0.023851,0.035113,0.108051,0.257454
4,0.009411,0.010827,0.010165,0.011324,0.012626,0.014846,0.016895,0.019971,0.023851,0.035113,0.108051,0.257454
5,0.008880,0.009777,0.010013,0.011105,0.012692,0.014291,0.016856,0.019351,0.024122,0.028552,0.054911,0.064426
6,0.007501,0.008786,0.009424,0.010595,0.012147,0.013845,0.016118,0.018703,0.024015,0.029533,0.040670,0.046477
7,0.006383,0.007796,0.008449,0.009777,0.011263,0.012483,0.014736,0.017451,0.021221,0.027563,0.034851,0.037926

In [56]:
xt = np.array(xt_grid)

In [57]:
xt

array([[0.00638303, 0.00779616, 0.00844854, 0.00977659, 0.01126267,
        0.01248344, 0.01473596, 0.0174506 , 0.02122129, 0.02756312,
        0.03485072, 0.0379259 ],
       [0.00750072, 0.00878589, 0.00942382, 0.0105949 , 0.01214719,
        0.0138454 , 0.01611813, 0.01870347, 0.02401521, 0.02953272,
        0.04066992, 0.04647721],
       [0.0088799 , 0.00977745, 0.01001304, 0.01110462, 0.01269174,
        0.01429128, 0.01685596, 0.01935132, 0.0241224 , 0.02855202,
        0.05491138, 0.06442595],
       [0.00941056, 0.01082722, 0.01016549, 0.01132376, 0.01262646,
        0.01484598, 0.01689528, 0.0199707 , 0.02385149, 0.03511326,
        0.10805102, 0.25745362],
       [0.00941056, 0.01082722, 0.01016549, 0.01132376, 0.01262646,
        0.01484598, 0.01689528, 0.0199707 , 0.02385149, 0.03511326,
        0.10805102, 0.25745362],
       [0.0088799 , 0.00977745, 0.01001304, 0.01110462, 0.01269174,
        0.01429128, 0.01685596, 0.01935132, 0.0241224 , 0.02855202,
        0.05491138, 0.06442595],
       [0.00750072, 0.00878589, 0.00942382, 0.0105949 , 0.01214719,
        0.0138454 , 0.01611813, 0.01870347, 0.02401521, 0.02953272,
        0.04066992, 0.04647721],
       [0.00638303, 0.00779616, 0.00844854, 0.00977659, 0.01126267,
        0.01248344, 0.01473596, 0.0174506 , 0.02122129, 0.02756312,
        0.03485072, 0.0379259 ]])

In [58]:
xt_rows, xt_cols = xt.shape

In [62]:
df['x1_bin'] = pd.cut(df['x'],bins = xt_cols, labels = False)
df['x2_bin'] = pd.cut(df['endX'],bins = xt_cols, labels = False)
df['y1_bin'] = pd.cut(df['y'],bins = xt_rows, labels = False)
df['y2_bin'] = pd.cut(df['endY'],bins = xt_rows, labels = False)

C:\Users\sivas\AppData\Local\Temp\ipykernel_1052\4042125900.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['x1_bin'] = pd.cut(df['x'],bins = xt_cols, labels = False)
C:\Users\sivas\AppData\Local\Temp\ipykernel_1052\4042125900.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['x2_bin'] = pd.cut(df['endX'],bins = xt_cols, labels = False)
C:\Users\sivas\AppData\Local\Temp\ipykernel_1052\4042125900.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['y1_bin'] = pd.cut(df['y'],bins = xt_rows, labels = False)
C:\Users\sivas\AppData\Local\Temp\ipykernel_1052\4042125900.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['y2_bin'] = pd.cut(df['endY'],bins = xt_rows, labels = False)

In [63]:
df.head()

,minute,second,teamId,x,y,period,type,outcome,playerId,endX,endY,x1_bin,x2_bin,y1_bin,y2_bin
2,0,0.0,Manchester United,49.9,50.0,FirstHalf,Pass,Successful,18.0,31.5,59.6,5,3,4,4
119,6,11.0,Manchester United,65.4,96.8,FirstHalf,Pass,Successful,18.0,63.3,87.8,7,7,7,7
130,6,55.0,Manchester United,69.8,30.3,FirstHalf,Pass,Successful,18.0,74.4,18.8,8,9,2,1
133,7,1.0,Manchester United,84.3,23.3,FirstHalf,Pass,Successful,18.0,86.0,20.0,10,10,1,1
185,12,20.0,Manchester United,39.0,64.8,FirstHalf,Pass,Successful,18.0,32.8,72.9,3,3,5,5

In [ ]:
df["start_zone_value"] = df[['x1_bin','y1_bin']],apply(lambda x: xt[x[1]][x[0]], axis = 1)